services:
  api:
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/code
  ui:
    build: ./ui
    ports:
      - 8080:8080
    volumes:
      - ./ui:/code
  elasticsearch:
    image: elasticsearch:8.17.0
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    profiles:
      - debug
    image: kibana:8.17.0
    ports:
      - 5601:5601
volumes:
  esdata:
    driver: local
networks:
  default:
    name: search-demo