services:
  elasticsearch:
    image: elasticsearch:8.17.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    profiles:
      - debug
    image: kibana:8.17.0
    ports:
      - 5601:5601
volumes:
  esdata:
    driver: local
